"""New module whole lookup

Revision ID: 24ca0a8f56f4
Revises: d782691e27df
Create Date: 2025-08-19 11:12:30.973668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ca0a8f56f4'
down_revision = 'd782691e27df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whole_module_lookup', schema=None) as batch_op:
        batch_op.create_index('whole_mod_key_lookup', ['panel_name', 'key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whole_module_lookup', schema=None) as batch_op:
        batch_op.drop_index('whole_mod_key_lookup')

    # ### end Alembic commands ###
