"""Added cell number

Revision ID: c4aa094d6fcb
Revises: aca713f598a2
Create Date: 2025-08-13 14:45:05.697483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aa094d6fcb'
down_revision = 'aca713f598a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_cells', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_panel', schema=None) as batch_op:
        batch_op.drop_column('num_cells')

    # ### end Alembic commands ###
