"""Adding diodes to customs

Revision ID: d782691e27df
Revises: c4aa094d6fcb
Create Date: 2025-08-18 13:30:17.132809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd782691e27df'
down_revision = 'c4aa094d6fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_panel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_diodes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_panel', schema=None) as batch_op:
        batch_op.drop_column('num_diodes')

    # ### end Alembic commands ###
