"""Add max power

Revision ID: f8428895c0a4
Revises: 
Create Date: 2025-08-11 09:55:52.467354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8428895c0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cell_data', schema=None) as batch_op:
        batch_op.create_index('idx_cell_lookup', ['panel_name', 'temperature', 'irradiance'], unique=False)

    with op.batch_alter_table('cell_lookup', schema=None) as batch_op:
        batch_op.create_index('cell_key_lookup', ['panel_name', 'key'], unique=False)

    with op.batch_alter_table('module_data', schema=None) as batch_op:
        batch_op.create_index('idx_voltage_lookup', ['kt', 'iph', 'isat', 'n', 'Rs', 'Rp', 'current'], unique=False)

    with op.batch_alter_table('module_lookup', schema=None) as batch_op:
        batch_op.create_index('mod_key_lookup', ['panel_name', 'key'], unique=False)

    with op.batch_alter_table('panel_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_power', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panel_info', schema=None) as batch_op:
        batch_op.drop_column('max_power')

    with op.batch_alter_table('module_lookup', schema=None) as batch_op:
        batch_op.drop_index('mod_key_lookup')

    with op.batch_alter_table('module_data', schema=None) as batch_op:
        batch_op.drop_index('idx_voltage_lookup')

    with op.batch_alter_table('cell_lookup', schema=None) as batch_op:
        batch_op.drop_index('cell_key_lookup')

    with op.batch_alter_table('cell_data', schema=None) as batch_op:
        batch_op.drop_index('idx_cell_lookup')

    # ### end Alembic commands ###
